version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invideo_app
    ports:
      - "4000:4000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
